"""Generate examples/sample_exchange.md — a worked wire exchange with REAL hashes.

Every hash in the generated file is computed by the reference constructions in
``verify_vectors.py`` (stdlib only). Re-run this script to regenerate the file; if your own
implementation produces different bytes for the same inputs, it is not conformant.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from verify_vectors import canonical_hash, ref_commit, ref_derive_starts, ref_state_hash

OUT = Path(__file__).parent / "sample_exchange.md"

CARD = {
    "protocol": "league/0.1",
    "match_id": "2026-08-01-aleph-vs-bet",
    "groups": {"group_1": "Team-Aleph", "group_2": "Team-Bet"},
    "urls": {
        "group_1_cop": "https://aleph.example/cop/mcp",
        "group_1_thief": "https://aleph.example/thief/mcp",
        "group_2_cop": "https://bet.example/cop/mcp",
        "group_2_thief": "https://bet.example/thief/mcp",
    },
    "grid": [10, 10],
    "rounds": 25,
    "num_games": 6,
    "swap_at": 3,
    "max_barriers": 0,
    "disclosure": "A",
    "scent_k": None,
    "seed": "league-spec-v0.1-example",
    "scheduled_utc": "2026-08-01T18:00:00Z",
    "timeouts": {"per_ply_seconds": 120, "per_subgame_seconds": 1800, "max_messages": 200},
}
CONFIG_SHA = canonical_hash(CARD)

N = 10
cop_start, thief_start = ref_derive_starts(CARD["seed"], 0, N)


def step(pos: list[int], dr: int, dc: int) -> list[int]:
    """A legal 8-dir step clamped to the board (keeps the example inside a 10x10 grid)."""
    return [min(max(pos[0] + dr, 0), N - 1), min(max(pos[1] + dc, 0), N - 1)]


# Three plies of sub-game 0 (thief-first): thief ply 0, cop ply 1, thief ply 2.
thief_p0 = step(thief_start, 1, 0)
cop_p1 = step(cop_start, -1, 1)
thief_p2 = step(thief_p0, 1, 1)

plies = [
    ("thief", 0, -1, thief_p0, "a1b2c3d4e5f60718"),
    ("cop", 1, 0, cop_p1, "00112233445566778899aabbccddeeff"),
    ("thief", 2, 1, thief_p2, "deadbeef00c0ffee"),
]

def trailer(ply_no: int, ack: int, move: list[int], nonce: str) -> str:
    t = {
        "v": 1,
        "game": 0,
        "ply": ply_no,
        "ack": ack,
        "move": move,
        "commit": ref_commit(move, nonce),
        "nonce": nonce,
        "reveal": None,
        "state": ref_state_hash([], "cop" if ply_no % 2 == 0 else "thief", ply_no + 1),
    }
    return json.dumps(t, separators=(",", ":"))


PROSE = {
    0: "I'm on the move. You'll have to do better than waiting in a corner, officer.\n"
       "My move and commitment are below, as per the league protocol.",
    1: "Bold words for someone leaving footprints. I'm sweeping toward the center\n"
       "to cut off your escape lanes. Move block below.",
    2: "Center, you say? Then you won't mind that I'm heading somewhere else\n"
       "entirely. Committed below.",
}

HELLO_1 = {"v": 1, "hello": {"protocol": "league/0.1", "config_sha256": CONFIG_SHA, "group": "Team-Aleph"}}
HELLO_2 = {"v": 1, "hello": {"protocol": "league/0.1", "config_sha256": CONFIG_SHA, "group": "Team-Bet"}}

REPORT_STUB = {"report_type": "bonus_game", "totals_by_group": {"Team-A": 80, "Team-B": 60}}

md = f"""# Worked example — one match setup + three plies + settlement

**Every hash below is real.** This file is generated by `gen_sample_exchange.py`, which uses only
the reference constructions in `verify_vectors.py`. Re-run the script to regenerate it; reproduce
the hashes with your own implementation to check your conformance on a realistic flow.

Scenario: sub-game 0 of a Mode A (full-disclosure) match on a 10x10 board. Team-Aleph is the cop,
Team-Bet is the thief (thief moves first, so the thief owns even plies).

## 1. The match card (SPEC §4.1)

```json
{json.dumps(CARD, indent=2)}
```

Canonical hash of the card (SPEC §2) — both sides must compute the same value:

```
config_sha256 = {CONFIG_SHA}
```

## 2. Start cells from the seed (SPEC §6.4)

`derive_starts("{CARD["seed"]}", index=0, n={N})` gives:

```
cop start   = {cop_start}
thief start = {thief_start}
```

## 3. Ply-zero handshake (SPEC §4.3)

Team-Aleph -> Team-Bet's thief mailbox (prose + trailer, one `deliver_message` string):

```
Hello Team-Bet! Aleph here, confirming we are ready to start series
2026-08-01-aleph-vs-bet as agreed. Our trailer carries the protocol
version and our hash of the match card - please verify it matches yours.
---LEAGUE-v1---
{json.dumps(HELLO_1, separators=(",", ":"))}
```

Team-Bet replies symmetrically:

```
---LEAGUE-v1---
{json.dumps(HELLO_2, separators=(",", ":"))}
```

Both `config_sha256` values match -> the match may begin. If they differ, nothing starts.

## 4. Three in-game plies (SPEC §5, Mode A)

"""

for role, ply_no, ack, move, nonce in plies:
    sender = "Team-Bet (thief)" if role == "thief" else "Team-Aleph (cop)"
    commit_hash = ref_commit(move, nonce)
    state = ref_state_hash([], "cop" if ply_no % 2 == 0 else "thief", ply_no + 1)
    md += f"""### Ply {ply_no} — {sender} moves to `{move}`

```
{PROSE[ply_no]}
---LEAGUE-v1---
{trailer(ply_no, ack, move, nonce)}
```

Receiver's checks (SPEC §8.1): trailer parses -> `game`/`ply` are the expected next block ->
`commit == sha256_canonical({{"nonce":"{nonce}","pos":{json.dumps(move)}}})` = `{commit_hash[:16]}...` ✓ ->
apply `{move}` to the local replica -> recompute
`state_hash([], "{"cop" if ply_no % 2 == 0 else "thief"}", {ply_no + 1})` = `{state[:16]}...` and compare with the trailer's `state` ✓.

"""

md += f"""## 5. Settlement (SPEC §9)

After the last sub-game each side builds its report from its own log, canonicalizes, hashes, and
exchanges only the hash. E.g. for an (illustrative, schema-TBD) report body
`{json.dumps(REPORT_STUB, separators=(",", ":"))}` both sides would send:

```
REPORT_SHA:{canonical_hash(REPORT_STUB)}
```

Byte-identical hashes -> both teams email the same report. Any mismatch -> the escalation in
SPEC §9 step 4. Nothing is ever emailed without a confirmed match.

## Notes for implementers (and their LLM assistants)

- The prose above the fence is interpreted by the receiving agent's LLM; it may bluff (the thief
  lies at ply 2). The trailer may not: it is constructed programmatically, and the receiver
  verifies it mechanically without any LLM involvement.
- `move_count` passed to `state_hash` is plies *completed* (ply 0 -> 1, ply 1 -> 2, ...), and
  `turn` is the role to move *next* — that's why ply 0's state frame is `("cop", 1)`.
- In this example barriers are disabled (`max_barriers: 0`), so `barriers` is always `[]` in the
  state frame.
"""

OUT.write_text(md, encoding="utf-8")
print(f"wrote {OUT.name} ({len(md)} chars); config_sha={CONFIG_SHA[:16]}..., starts cop={cop_start} thief={thief_start}")
